#ifndef __IOTAAP_DEFINES_H__
#define __IOTAAP_DEFINES_H__

#define ONBOARD_LED1 15
#define ONBOARD_LED2 2
#define ONBOARD_BUT1 0
#define ONBOARD_BUT2 25
#define BATSENS_PIN 36
#define ONBOARD_BUZZER 32
#define ADC_SAMPLES 1
#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
#define ONBOARD_DEBOUNCE_TIME 20
#define WIFI_TIMEOUT 5000
#define MQTT_TIMEOUT 3000
#define ACCELEROMETER_X_PIN 33
#define ACCELEROMETER_Y_PIN 34
#define ACCELEROMETER_Z_PIN 35

#endif