//#define ENABLE_ADC
//#define ENABLE_ACCELEROMETER
//#define ENABLE_OLED
//#define ENABLE_BUZZER
//#define ENABLE_HALL
//#define ENABLE_SERIAL
//#define ENABLE_WIFI
//#define ENABLE_MQTT
//#define ENABLE_TCP
//#define ENABLE_DAC
//#define ENABLE_PWM
//#define ENABLE_KAI
//#define ENABLE_DEBOUNCE
//#define ENABLE_BTSERIAL
//#define ENABLE_JSON
//#define ENABLE_TCPSERVER
//#define ENABLE_TCPCLIENT